### ISSUE TITLE
error after creating first account

### ISSUE THREAD

**Issue by rich1488** [hendrikbgr/YandexMail-Account-Creator#61]
it creates the first account great. then stops after, like it doesn't loop or something

**Comment by taylorjayoung** [comment]
Getting the same issue as above poster. 

More specifically the below error message.
```
Traceback (most recent call last):
  File "/Users/tayloryoung/2021/YandexMail-Account-Creator/creator.py", line 218, in <module>
    wait.until(EC.element_to_be_clickable(
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

```

 I'm not familiar with Python so it's difficult to debug. But the first account is created successfully, logged into the terminal, and then the Timeout error occurs.

**Comment by rich1488** [comment]
Yea it won't start on the next account. I'm hoping the developer is still around or if someone can figure out a fix for this, I can't find any other email creators like this anywhere.

**Comment by taylorjayoung** [comment]
Try shooting him a dm on Twitter, he lists his handle in the ReadMe.md.  Yeah, I wish I knew python. From what I can see, the scripts are dependent on very specific DOM locations for elements that they take actions on. So if anything changes in the html (which happens often) it would make these scripts obsolete.

**Comment by rich1488** [comment]
I actually did tweet him but he hasnt been active since july

**Comment by kremerNK** [comment]
you can comment out lines 289 through 363. also modify the `csvData` list and remove the `appPassword `. it works for now. not sure what those parts of the script are doing, so apologies to the creator if they're an essential part

**Comment by rich1488** [comment]
someone posted a fix and either deleted their message or author did?

**Comment by kremerNK** [comment]
i posted a fix and deleted it because it didn't work correctly. you can comment out lines 289-363 and remove `appPassword` from `csvData` list, and the script will seemingly create the accounts. but after trying to log in, none of the accounts were actually created. if you have python knowledge, you could play around with this and probably make it work. i no longer need it, so won't be toying with modifications

**Comment by rich1488** [comment]
> i posted a fix and deleted it because it didn't work correctly. you can comment out lines 289-363 and remove `appPassword` from `csvData` list, and the script will seemingly create the accounts. but after trying to log in, none of the accounts were actually created. if you have python knowledge, you could play around with this and probably make it work. i no longer need it, so won't be toying with modifications
> 
> i think you just need to get it past the "Add picture" html page, which would be the dashboard. once it's at the dashboard, then figure out where the script breaks and just remove that part so it keeps looping
> 
> it sometimes broke at the registration page also, when yandex required a phone number. but that was a rare outcome

What was the issue with accounts being created?

I did notice that the accounts this does make, they are auto locked and need to be recovered.

**Comment by hendrikbgr** [comment]
Hello together!
The script did work for a while and it can be fixed easily but all accounts created with this script sadly get flagged by yandex and they will ask you to confirm the account with a phone number. I tried multiple things to prevent this flagging but could not find a solution.

**Comment by UWUplus** [comment]
@hendrikbgr Just stumbled over this and tried it out, the account created works fine, however I use residential proxies, so that could be the cause. I'd love to see the script get fixed, if you find the time to get around to do that.

**Comment by UWUplus** [comment]
Fixed it myself, replace everything from line 289 to 362 with this:
```
        wait.until(EC.element_to_be_clickable(
            (By.XPATH, '/html/body/div/div/div[1]/div[2]/main/div/div/div/div[3]/span/a'))).click()

        # Open Passwords accordion
        wait.until(EC.element_to_be_clickable(
            (By.XPATH, '/html/body/div/div/div[2]/div[3]/main/div/div/div/div[1]/div/div/div/div[4]/div[2]/div[1]/div[2]'))).click()
        print("test1")
        sleep(5)

        wait.until(EC.element_to_be_clickable(
            (By.XPATH, '/html/body/div/div/div[2]/div[3]/main/div/div/div/div[1]/div/div/div/div[4]/div[2]/div[2]/div[3]/div/div[1]/div/span/span'))).click()

        wait.until(EC.element_to_be_clickable(
            (By.XPATH, '/html/body/div[2]/div[1]/div/div/div/div/div/div[2]/div/button'))).click()
        
        wait.until(EC.element_to_be_clickable(
            (By.XPATH, '/html/body/div[2]/div[1]/div/div/div/div/div/div[3]/div/div[1]/button'))).click()

        wait.until(EC.element_to_be_clickable(
            (By.XPATH, '/html/body/div[3]/div[1]/div/div/div/div/div[2]/div[2]/ul/li[1]/span[1]/span'))).click()

        appName = 'App for Imap'

        final = wait.until(EC.element_to_be_clickable(
            (By.XPATH, '/html/body/div[3]/div[1]/div/div/div/div/div[2]/div[3]/div[1]/span/input')))
        type_me(final, appName)
        
        wait.until(EC.element_to_be_clickable(
            (By.XPATH, '/html/body/div[3]/div[1]/div/div/div/div/div[2]/div[4]/div/div[1]/button'))).click()
        sleep(2)

        appPassword = driver.find_element_by_xpath('/html/body/div[3]/div[1]/div/div/div/div/div[2]/div[1]/div[1]/span').text

        wait.until(EC.element_to_be_clickable(
            (By.XPATH, '/html/body/div[3]/div[1]/div/div/div/div/div[2]/div[2]/div[2]/button'))).click()
```

Will look into creating a pull request when I'm done commenting the steps, would also add support for proxies without authentication.

**Comment by hendrikbgr** [comment]
@UWUplus could you send me a DM on Twitter @hendrik_bgr so we can discuss this further? Just checked your code and it all seems to be working, thanks for that! Are those accounts you creating still working? Mine only got flagged up to 24hrs after creation.

**Comment by rich1488** [comment]
Thank you for this! Are the accounts still getting locked after creation? They seem to need to be restored or w/e

Anyone know how I can use proxies that don't need username:pass? I tried using `proxy:port::` leaving it blank of user/pass but that doesnt seem to work
